#!/usr/bin/python3

import numpy

import sys
sys.path.append('..')
import fit_res
from example_plot import plot_fsweeps

# Example 2: linear oscillator, multiple frequency sweeps at multiple drives

# Load data (file contains 5 columns, TT,FF,XX,YY,DD, select only what we need)
(FF,XX,YY,DD) = numpy.loadtxt('example2.txt', usecols=(1,2,3,4), unpack=1)

# Do fit:
do_fit=1
const_bg=1
linear_bg=1
coord=0

fit = fit_res.fit_lin(FF,XX,YY,DD, do_fit=do_fit,
     const_bg=const_bg, linear_bg=linear_bg, coord=coord)

# Plot:
plot_fsweeps("example2.png", fit, FF,XX,YY,DD, plot_bg=0)

# Print parameters:
print('Amp/Drive = %.3e + %.3e*i'%(fit.pars[0],fit.pars[1]))
print('|Amp/Drive| = %.3e'%(numpy.hypot(fit.pars[0],fit.pars[1])))
print('f0 = %.3f'%(fit.pars[2]))
print('df = %.3f'%(fit.pars[3]))
n=4
if const_bg:
  print('constant BG/Drive = %.3e + %.3e*i'%(fit.pars[n],fit.pars[n+1]))
  n+=2
if linear_bg:
  print('linear bg/Drive = (%.3e + %.3e*i)*(f-f0)'%(fit.pars[n],fit.pars[n+1]))
  n+=2
