#!/usr/bin/python3

import numpy

import sys
sys.path.append('..')
import fit_res
from example_plot import plot_fsweeps

# Example 4: Oscillator in ballistic B phase

# Load data (file contains 5 columns, TT,FF,XX,YY,DD, select only what we need)
(FF,XX,YY,DD) = numpy.loadtxt('example4.txt', usecols=(1,2,3,4), unpack=1)

# Do fit:
do_fit=1
const_bg=1
linear_bg=0
coord=0

fit = fit_res.fit_bphase(FF,XX,YY,DD, do_fit=do_fit,
     const_bg=const_bg, linear_bg=linear_bg, coord=coord)

# Plot:
plot_fsweeps("example4.png", fit, FF,XX,YY,DD, plot_bg=0, both_dir=1)

# Print parameters:
print('Amp/Drive = %.3e + %.3e*i'%(fit.pars[0],fit.pars[1]))
print('|Amp/Drive| = %.3e'%(numpy.hypot(fit.pars[0],fit.pars[1])))
print('f0 = %.3f'%(fit.pars[2]))
print('df = %.3f'%(fit.pars[3]))
print('a = %.3e'%(fit.pars[4]))
n=5
if const_bg:
  print('constant BG = %.3e + %.3e*i'%(fit.pars[n],fit.pars[n+1]))
  n+=2
if linear_bg:
  print('linear bg = (%.3e + %.3e*i)*(f-f0)'%(fit.pars[n],fit.pars[n+1]))
  n+=2
