#!/usr/bin/python3

import numpy

import sys
sys.path.append('..')
import fit_res
from example_plot import plot_fsweeps

# Example 2: linear oscillator, multiple frequency sweeps at multiple drives

# Load data (file contains 5 columns, TT,FF,XX,YY,DD, select only what we need)
(FF,XX,YY,DD) = numpy.loadtxt('example2.txt', usecols=(1,2,3,4), unpack=1)

# Do fit:
do_fit=1
const_bg=1
linear_bg=1
coord=0

fit = fit_res.fit_lin(FF,XX,YY,DD, do_fit=do_fit,
     const_bg=const_bg, linear_bg=linear_bg, coord=coord)

# Plot:
plot_fsweeps("example2.png", fit, FF,XX,YY,DD, plot_bg=0)

# Print parameters:
print('Amp/Drive = {:.3e}'.format(fit.get_amp()))
print('|Amp|/Drive = %.3e'%(abs(fit.get_amp())))
print('f0 = %.3f'%(fit.get_f0()))
print('df = %.3f'%(fit.get_df()))
print('constant BG = {:.3e}'.format(fit.get_cbg()))
print('linear BG   = {:.3e}'.format(fit.get_lbg()))
