#!/usr/bin/python3

import numpy

import sys
sys.path.insert(0,'..')
import fit_res
from example_plot import plot_fsweeps

# Example 3: Duffing oscillator, multiple frequency sweeps at multiple drives
# Note that experimental data is not exactly a Duffing oscillator.

# Load data (file contains 5 columns, TT,FF,XX,YY,DD, select only what we need)
(FF,XX,YY,DD) = numpy.loadtxt('example3.txt', usecols=(1,2,3,4), unpack=1)

# Do fit:
fit = fit_res.fit_duff(FF,XX,YY,DD, do_fit=1,
     cbg=0, lbg=0, coord=0)

# Plot:
plot_fsweeps("example3.png", fit, FF,XX,YY,DD, plot_bg=0, both_dir=1)

# Print parameters:
print('Amp/Drive = {:.3e}'.format(fit.get_amp()))
print('|Amp|/Drive = %.3e'%(abs(fit.get_amp())))
print('f0 = %.3f'%(fit.get_f0()))
print('df = %.3f'%(fit.get_df()))
print('a  = %.3e'%(fit.get_a()))
print('cbg0 = {:.3e}'.format(fit.get_cbg0()))
print('cbg  = {:.3e}'.format(fit.get_cbg()))
print('lbg  = {:.3e}'.format(fit.get_lbg()))
