#!/usr/bin/python3

import numpy

import sys
sys.path.insert(0,'..')
import fit_res
from example_plot import plot_fsweeps

# Example 2: linear oscillator, multiple frequency sweeps at multiple drives

# Load data (file contains 5 columns, TT,FF,XX,YY,DD, select only what we need)
(FF,XX,YY,DD) = numpy.loadtxt('example2.txt', usecols=(1,2,3,4), unpack=1)

# Do fit:
fit = fit_res.fit_lin(FF,XX,YY,DD, do_fit=1,
     cbg=1, lbg=1, coord=0)

# Plot:
plot_fsweeps("example2.png", fit, FF,XX,YY,DD, plot_bg=0)

# Print parameters:
print('Amp/Drive = {:.3e}'.format(fit.get_amp()))
print('|Amp|/Drive = %.3e'%(abs(fit.get_amp())))
print('f0 = %.3f'%(fit.get_f0()))
print('df = %.3f'%(fit.get_df()))
print('cbg0 = {:.3e}'.format(fit.get_cbg0()))
print('cbg  = {:.3e}'.format(fit.get_cbg()))
print('lbg  = {:.3e}'.format(fit.get_lbg()))
