#!/usr/bin/python3

import numpy

import sys
sys.path.insert(0,'..')
import fit_res
from example_plot import plot_fsweeps

# Example 4: Oscillator in ballistic B phase

# Load data (file contains 5 columns, TT,FF,XX,YY,DD, select only what we need)
(FF,XX,YY,DD) = numpy.loadtxt('example4.txt', usecols=(1,2,3,4), unpack=1)

# Do fit:
fit = fit_res.fit_bphase(FF,XX,YY,DD, do_fit=1,
     cbg0=1, cbg=1, lbg=0, coord=0)

# Plot:
plot_fsweeps("example4.png", fit, FF,XX,YY,DD, plot_bg=0, both_dir=1)

# Print parameters:
print('Amp/Drive = {:.3e}'.format(fit.get_amp()))
print('|Amp|/Drive = %.3e'%(abs(fit.get_amp())))
print('f0 = %.3f'%(fit.get_f0()))
print('df = %.3f'%(fit.get_df()))
print('v0  = %.3e'%(fit.get_v0()))
print('cbg0 = {:.3e}'.format(fit.get_cbg0()))
print('cbg  = {:.3e}'.format(fit.get_cbg()))
print('lbg  = {:.3e}'.format(fit.get_lbg()))
