#!/usr/bin/python3

import numpy

import sys
sys.path.append('..')
import fit_res
from example_plot import plot_fsweeps

# Example 1: fit multiple frequency sweeps at a single drive

# Load data (file contains 5 columns, TT,FF,XX,YY,DD, select only what we need)
(FF,XX,YY) = numpy.loadtxt('example1.txt', usecols=(1,2,3), unpack=1)

# Do fit:
do_fit=1
cbg=1
lbg=1
coord=0

fit = fit_res.fit_lin(FF,XX,YY, do_fit=do_fit,
     cbg=cbg, lbg=lbg, coord=coord)

# Plot:
plot_fsweeps("example1.png", fit, FF,XX,YY)

# Print parameters:
print('Amp = {:.3e}'.format(fit.get_amp()))
print('|Amp| = %.3e'%(abs(fit.get_amp())))
print('f0 = %.3f'%(fit.get_f0()))
print('df = %.3f'%(fit.get_df()))
print('constant BG = {:.3e}'.format(fit.get_cbg()))
print('linear BG   = {:.3e}'.format(fit.get_lbg()))
